services:
  #* DATABASE (PostgreSQL)
  postgres:
    image: postgres:15-alpine
    container_name: tf_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - taskflow_app

  #* Cache (Redis)
  redis:
    image: redis:alpine
    container_name: tf_redis
    restart: always
    environment:
      - REDIS_PORT=${REDIS_PORT}
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    networks:
      - taskflow_app
    volumes:
      - redis_data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD}
volumes:
  pgdata:
  redis_data:

networks:
  taskflow_app: